What is Pytorch?


    Machine Learning Framework


    Used for research prototyping


    Used for deployment to production


    All code is done in python 


Tensors

Multi-Dimensional Arrays/Vectors

In [1]:
import torch

In [3]:
z = torch.ones(5,3) #tensor use ones function to specify dimension of matrix with ones
print(z) 
print(z.dtype) #by default all tensors are 32 bit floats

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [7]:
#change the default data type in each tensor 
i = torch.ones((5,3), dtype = torch.int16)
print(i) # will specify dype because this is not default params 

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [8]:
torch.manual_seed(1729) #manual seed to control randomness
r1 = torch.rand(2,2)
print('A random tensor: ')
print(r1)

r2 = torch.rand(2,2)
print('\nA different random tensor')
print(r2)

#go back to the original seed and get the same tensor

torch.manual_seed(1729) 
r3 = torch.rand(2,2)
print('A random tensor ')
print(r3)



A random tensor: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
A random tensor 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [11]:
#Arithmetic with pytorch tensors

ones = torch.ones(2,3)
twos = ones*2
print(twos)

#adding two tensores of the same shape

threes = ones + twos
print(threes)
print(threes.shape)

#add two tensors of different shape
r1 = torch.rand(2,3)
r2 = torch.rand(3,2)

try:
    r3 = r1 + r2
    print(r2)
    print(r2.shape)
except:
    print("Error, dimensionality does not match")




tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])
Error, dimensionality does not match


In [24]:
#mathematical operations

r = (torch.rand(2,2) - 0.5) * 2
print("Random matrix")
print(r)

#abs
print("Absolute Value: ")
print(torch.abs(r))

#trig functions
print("arcsin: ")
print(torch.arcsin(r))

#Lin alg
print("determinant of r: ")
print(torch.det(r))

#stats - stddev, means, etc.

#max element
print("max elem: ")
print(torch.max(r))

Random matrix
tensor([[ 0.9767, -0.0476],
        [ 0.4484, -0.8447]])
Absolute Value: 
tensor([[0.9767, 0.0476],
        [0.4484, 0.8447]])
arcsin: 
tensor([[ 1.3543, -0.0476],
        [ 0.4650, -1.0060]])
determinant of r: 
tensor(-0.8037)
max elem: 
tensor(0.9767)
